spring:
# 静的コンテンツのキャッシュ対応
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: false
# Postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    sql-script-encoding: UTF-8
