-- DROP TABLE milscm4.mt_shinryo_koi_fuka_temp;
CREATE TABLE milscm4.mt_shinryo_koi_fuka_temp(
    koshin_kubun TEXT NOT NULL                  -- 更新区分
    , master_type TEXT NOT NULL                 -- マスター種別
    , shinryo_koi_code TEXT NOT NULL            -- 診療行為コード
    , shinryo_koi_kanji_name_ketasu TEXT        -- 診療行為省略漢字有効桁数
    , shinryo_koi_kanji_name TEXT               -- 診療行為省略漢字名称
    , shinryo_koi_kana_name_ketasu TEXT         -- 診療行為省略カナ有効桁数
    , shinryo_koi_kana_name TEXT                -- 診療行為省略カナ名称
    , data_standard_code TEXT                   -- データ規格コード
    , data_standard_ketasu TEXT                 -- データ規格漢字有効桁数
    , data_standard_name TEXT                   -- データ規格漢字名称
    , gen_tensu_shikibetsu TEXT                 -- 新又は現点数識別
    , gen_tensu TEXT                            -- 新又は現点数
    , nyugai_tekiyo_kubun TEXT                  -- 入外適用区分
    , aged_tekiyo_kubun TEXT                    -- 後期高齢者医療適用区分
    , tensuran_shikibetsu_nyuingai TEXT         -- 点数欄集計先識別（入院外）
    , hokatsu_kensa TEXT                        -- 包括対象検査
    , reserve1 TEXT                             -- 予備1
    , dpc_tekiyo_kubun TEXT                     -- DPC適用区分
    , clinic_kubun TEXT                         -- 病院・診療所区分
    , shujutsu_kasan_kubun TEXT                 -- 画像等手術支援加算区分
    , iryo_kansatsu_kubun TEXT                  -- 医療観察法対象区分
    , kango_kasan TEXT                          -- 看護加算
    , masui_shujutsu_kubun TEXT                 -- 麻酔識別区分
    , reserve2 TEXT                             -- 予備2
    , shobyo_kanren_kubun TEXT                  -- 傷病名関連区分
    , reserve3 TEXT                             -- 予備3
    , jitsu_days TEXT                           -- 実日数
    , days_times TEXT                           -- 日数・回数
    , iyakuhin_kanren_kubun TEXT                -- 医薬品関連区分
    , kizami_keisan_shikibetsu TEXT             -- きざみ値計算識別
    , kizami_low TEXT                           -- きざみ値下限値
    , kizami_up TEXT                            -- きざみ値上限値
    , kizami_value TEXT                         -- きざみ値
    , kizami_tensu TEXT                         -- きざみ点数
    , up_low_error TEXT                         -- 上下限エラー処理
    , up_times TEXT                             -- 上限回数
    , up_times_error TEXT                       -- 上限回数エラー処理
    , chu_kasan_code TEXT                       -- 注加算コード
    , chu_kasan_no TEXT                         -- 注加算通番
    , tsusoku_age TEXT                          -- 通則年齢
    , low_age TEXT                              -- 下限年齢
    , up_age TEXT                               -- 上限年齢
    , time_kasan_kubun TEXT                     -- 時間加算区分
    , tekigo_kubun TEXT                         -- 適合区分
    , facility_kijun TEXT                       -- 対象施設基準
    , nyuyoji_kasan_kubun TEXT                  -- 処置乳幼児加算区分
    , taijuji_kasan_kubun TEXT                  -- 極低出生体重児加算区分
    , nyuin_kihon_gensan_shikibetsu TEXT        -- 入院基本料等減算対象識別
    , donor_kubun TEXT                          -- ドナー分集計区分
    , kensa_handan_kubun TEXT                   -- 検査等実施判断区分
    , kensa_handan_group_kubun TEXT             -- 検査等実施判断グループ区分
    , teigen_kubun TEXT                         -- 逓減対象区分
    , sekizui_kasan_kubun TEXT                  -- 脊髄誘発電位測定等加算区分
    , keibu_kasan_kubun TEXT                    -- 頸部郭清術併施加算区分
    , hogoki_kasan_kubun TEXT                   -- 自動縫合器加算区分
    , gairai_kasan_kubun TEXT                   -- 外来管理加算区分
    , old_tensu_shikibetsu TEXT                 -- 旧点数識別
    , old_tensu TEXT                            -- 旧点数
    , kanji_henko_kubun TEXT                    -- 漢字名称変更区分
    , kana_henko_kubun TEXT                     -- カナ名称変更区分
    , kentai_comment TEXT                       -- 検体検査コメント
    , tsusoku_kasan_tensu TEXT                  -- 通則加算所定点数対象区分
    , hokatsu_teigen_kubun TEXT                 -- 包括逓減区分
    , choonpa_naishikyo_kasan_kubun TEXT        -- 超音波内視鏡加算区分
    , reserve4 TEXT                             -- 予備4
    , tensuran_shikibetsu_nyuin TEXT            -- 点数欄集計先識別（入院）
    , fungoki_kasan_kubun TEXT                  -- 自動吻合器加算区分
    , kokuji_shikibetsu_kubun1 TEXT             -- 告示等識別区分1
    , kokuji_shikibetsu_kubun2 TEXT             -- 告示等識別区分2
    , chiiki_kasan TEXT                         -- 地域加算
    , bed_su_kubun TEXT                         -- 病床数区分
    , facility_kijun_code1 TEXT                 -- 施設基準コード1
    , facility_kijun_code2 TEXT                 -- 施設基準コード2
    , facility_kijun_code3 TEXT                 -- 施設基準コード3
    , facility_kijun_code4 TEXT                 -- 施設基準コード4
    , facility_kijun_code5 TEXT                 -- 施設基準コード5
    , facility_kijun_code6 TEXT                 -- 施設基準コード6
    , facility_kijun_code7 TEXT                 -- 施設基準コード7
    , facility_kijun_code8 TEXT                 -- 施設基準コード8
    , facility_kijun_code9 TEXT                 -- 施設基準コード9
    , facility_kijun_code10 TEXT                -- 施設基準コード10
    , choonpa_sekkai_kasan_kubun TEXT           -- 超音波凝固切開装置等加算区分
    , tanki_shujutsu TEXT                       -- 短期滞在手術
    , shika_tekiyo_kubun TEXT                   -- 歯科適用区分
    , code_table_alphabet TEXT                  -- コード表用番号（アルファベット部）
    , kokuji_kanren_no_alphabet TEXT            -- 告示・通知関連番号（アルファベット部）
    , henko_ymd TEXT                            -- 変更年月日
    , haishi_ymd TEXT                           -- 廃止年月日
    , kohyo_junjo_no TEXT                       -- 公表順序番号
    , code_table_no_sho TEXT                    -- コード表用番号_章
    , code_table_no_bu TEXT                     -- コード表用番号_部
    , code_table_no_kubun TEXT                  -- コード表用番号_区分番号
    , code_table_no_edaban TEXT                 -- コード表用番号_枝番
    , code_table_no_koban TEXT                  -- コード表用番号_項番
    , kokuji_kanren_no_sho TEXT                 -- 告示・通知関連番号_章
    , kokuji_kanren_no_bu TEXT                  -- 告示・通知関連番号_部
    , kokuji_kanren_no_kubun TEXT               -- 告示・通知関連番号_区分番号
    , kokuji_kanren_no_edaban TEXT              -- 告示・通知関連番号_枝番
    , kokuji_kanren_no_koban TEXT               -- 告示・通知関連番号_項番
    , age1_kasan_low TEXT                       -- 年齢加算1下限年齢
    , age1_kasan_up TEXT                        -- 年齢加算1上限年齢
    , age1_kasan_koi_code TEXT                  -- 年齢加算1注加算診療行為コード
    , age2_kasan_low TEXT                       -- 年齢加算2下限年齢
    , age2_kasan_up TEXT                        -- 年齢加算2上限年齢
    , age2_kasan_koi_code TEXT                  -- 年齢加算2注加算診療行為コード
    , age3_kasan_low TEXT                       -- 年齢加算3下限年齢
    , age3_kasan_up TEXT                        -- 年齢加算3上限年齢
    , age3_kasan_koi_code TEXT                  -- 年齢加算3注加算診療行為コード
    , age4_kasan_low TEXT                       -- 年齢加算4下限年齢
    , age4_kasan_up TEXT                        -- 年齢加算4上限年齢
    , age4_kasan_koi_code TEXT                  -- 年齢加算4注加算診療行為コード
    , ido_kanren TEXT                           -- 異動関連
    , kihon_kanji_name TEXT                     -- 基本漢字名称
    , fukubiko_naishikyo_kasan TEXT             -- 副鼻腔手術用内視鏡加算
    , fukubiko_kotsunanbu_kasan TEXT            -- 副鼻腔手術用骨軟部組織切除機器加算
    , long_masui_kasan TEXT                     -- 長時間麻酔管理加算
    , tensu_kubun_no TEXT                       -- 点数表区分番号
    , monitoring_kasan TEXT                     -- モニタリング加算
    , toketsu_hozon_kasan TEXT                  -- 凍結保存同種組織加算
    , akusei_shuyo_kasan TEXT                   -- 悪性腫瘍病理組織標本加算
    , sogai_kotei_kasan TEXT                    -- 創外固定器加算
    , chouonpa_sessaku_kasan TEXT               -- 超音波切削機器加算
    , sashin_jiheisa_kasan TEXT                 -- 左心耳閉鎖術併施加算
    , gairai_kansen_taisaku_koujo_kubun TEXT    -- 外来感染対策向上加算等
    , jibi_inko_nyuyoji_kasan TEXT              -- 耳鼻咽喉科乳幼児処置加算
    , jibi_inko_shoni_koukin_tekisei_shiyou_shien_kasan TEXT -- 耳鼻咽喉科小児抗菌薬適正使用支援加算
    , sekkaisou_kyokusho_inatsu_heisa_shochi_kasan TEXT -- 切開創局所陰圧閉鎖処置機器加算
    , reserve5 TEXT                             -- 予備5
    , reserve6 TEXT                             -- 予備6
    , reserve7 TEXT                             -- 予備7
    , reserve8 TEXT                             -- 予備8
    , reserve9 TEXT                             -- 予備9
    , reserve10 TEXT                            -- 予備10
    , reserve11 TEXT                            -- 予備11
    , reserve12 TEXT                            -- 予備12
    , reserve13 TEXT                            -- 予備13
    , reserve14 TEXT                            -- 予備14
    , reserve15 TEXT                            -- 予備15
    , reserve16 TEXT                            -- 予備16
    , reserve17 TEXT                            -- 予備17
    , reserve18 TEXT                            -- 予備18
    , reserve19 TEXT                            -- 予備19
    , reserve20 TEXT                            -- 予備20
    , reserve21 TEXT                            -- 予備21
    , reserve22 TEXT                            -- 予備22
    , reserve23 TEXT                            -- 予備23
    , reserve24 TEXT                            -- 予備24
    , reserve25 TEXT                            -- 予備25
    , reserve26 TEXT                            -- 予備26
    , reserve27 TEXT                            -- 予備27
    , update_ymd TEXT NOT NULL                  -- データ登録日
);

ALTER TABLE ONLY milscm4.mt_shinryo_koi_fuka_temp ADD CONSTRAINT mt_shinryo_koi_fuka_temp_pkey PRIMARY KEY (koshin_kubun, shinryo_koi_code, update_ymd)
;

ALTER TABLE milscm4.mt_shinryo_koi_fuka_temp OWNER TO pgmisgrp1;
